### ISSUE TITLE
missing hex digit for \x

### ISSUE THREAD

**Issue by Qwertylex** [richfelker/totp.sh#3]
[alex@midgard ~]$ ./totp.sh < website.key
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
./totp2.sh: line 29: printf: missing hex digit for \x
028827
[alex@midgard ~]$ 

It produces a valid 2FA code which works fine...
but are these line 29 messages expected?

**Comment by Qwertylex** [comment]
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
GNU coreutils 8.32 March 2020

**Comment by richfelker** [comment]
Indeed this looks like a bug, a missing level of quoting in the inner `printf` call on line 22, which my version of `printf` silently ignored by treating the `\x` as a literal and which bash's ignored but with a warning. Changing it to `\\x` should fix it. I'll test and push a fix.

**Comment by richfelker** [comment]
Fixed by 81bdcd1b06.
